variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CLIENT_TIMEOUT: 600
  COMPOSE_HTTP_TIMEOUT: 600
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
stages:
  - build
  - test1
  - test2
  - deploy
  - notify
build_job:
  stage: build
  image: python:3.11
  script:
    - pip install -r requirements.txt
test_job:
  stage: test1
  image: python:3.11
  script:
    - echo "Testando a aplicacao flask"
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest || echo "Nenhum teste encontrado"
    - pytest --cov=. --cov-report=xml
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week

code_analysis:
  stage: test2
  image: sonarsource/sonar-scanner-cli:latest
  dependencies:
    - test_job
  script:
    - echo "Verificando artefatos do test_job"
    - pwd
    - ls -la
    - if [ -f coverage.xml ]; then cat coverage.xml; else echo "coverage.xml não encontrado"; fi
    - sonar-scanner -D sonar.python.coverage.reportPaths=coverage.xml

deploy_job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

  before_script:
    - echo "Removendo container antigo na porta 5000"
    - PORT_CONTAINERS=$(docker ps --filter "publish=5000" -q)
    - echo $PORT_CONTAINERS
    - |
      if [ -n "$PORT_CONTAINERS" ]; then
        docker stop $PORT_CONTAINERS
        docker rm $PORT_CONTAINERS
        sleep 5
      fi

  script:
    - echo "Fazendo deploy da aplicação Flask"
    - docker run -d -p 5000:5000 task-manager:latest
